
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   annotations:
       storageclass.kubernetes.io/is-default-class: "true"
   name: nutanix-volumes
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
  csi.storage.k8s.io/node-publish-secret-name: ntnx-secret 
  csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
  csi.storage.k8s.io/fstype: ext4
  #isSegmentedIscsiNetwork: is-segmented-iscsi-network
  flashMode: ENABLED
  storageContainer: SelfServiceContainer
  #chapAuth: ENABLED | DISABLED
  storageType: NutanixVolumes
  #whitelistIPMode: ENABLED/DISABLED  
  #whitelistIPAddr: ip-address
provisioner: csi.nutanix.com
reclaimPolicy: Delete
