apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: data-postgresql-prod-0
spec:
 storageClassName: nutanix-volumes
 dataSource:
   name: postgresql-snapshot-4
   kind: VolumeSnapshot
   apiGroup: snapshot.storage.k8s.io
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 8Gi
